version: '3'

services:
  
  node-master:
    build:
      context: .
      dockerfile: ./master/Dockerfile
    hostname: node-master
    networks:
      cluster:
        ipv4_address: 192.1.0.2
    depends_on:
      - node1
      - node2
    extra_hosts:
      - "node1:192.1.0.3"
      - "node2:192.1.0.4"

  node1:
    build:
      context: .
      dockerfile: ./nodes/Dockerfile
    image: worker-node
    hostname: node1
    networks:
      cluster:
        ipv4_address: 192.1.0.3
    extra_hosts:
      - "node-master:192.1.0.2"
      - "node2:192.1.0.4"

  node2:
    image: worker-node
    hostname: node2
    networks:
      cluster:
        ipv4_address: 192.1.0.4
    extra_hosts:
      - "node-master:192.1.0.2"
      - "node1:192.1.2.2"
    depends_on: 
      - node1

networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.1.0.0/16
